# Generated by Django 3.1.6 on 2021-04-20 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210420_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='Este post es genial, dale click para que aprendas cosas interesantes y alimente tu curiosidad'),
            preserve_default=False,
        ),
    ]
